-- DBUPDATE-031-0.SQL

-- Insert a new setting for OCR recognition
insert into T_CONFIG (CFG_ID_C, CFG_VALUE_C) values ('OCR_ENABLED', 'true');

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '31' where CFG_ID_C = 'DB_VERSION';

-- Create the registration request table
CREATE TABLE T_REGISTRATION_REQUEST ( REQ_ID_C VARCHAR(36) PRIMARY KEY, REQ_USERNAME_C VARCHAR(50) NOT NULL UNIQUE, REQ_PASSWORD_C VARCHAR(255) NOT NULL, REQ_EMAIL_C VARCHAR(100) NOT NULL UNIQUE, REQ_CREATEDATE_D TIMESTAMP NOT NULL );
ALTER TABLE T_REGISTRATION_REQUEST ADD COLUMN REQ_APPROVED_B BOOLEAN NOT NULL DEFAULT FALSE;